'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Calendar, Sun, Sunset, Moon, Zap, CheckCircle2, ChevronRight, Sparkles, Clock } from 'lucide-react';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

interface PlannerTask {
  id: string;
  title: string;
  time?: string;
  period: 'morning' | 'afternoon' | 'evening';
  done: boolean;
  aiGenerated: boolean;
  priority: 'high' | 'medium' | 'low';
}

const INITIAL_TASKS: PlannerTask[] = [
  { id: '1', title: 'Morning meditation (10 min)', time: '07:00', period: 'morning', done: false, aiGenerated: true, priority: 'high' },
  { id: '2', title: 'Review today\'s goals', time: '07:30', period: 'morning', done: false, aiGenerated: true, priority: 'high' },
  { id: '3', title: 'Drink 2 glasses of water', time: '08:00', period: 'morning', done: true, aiGenerated: true, priority: 'medium' },
  { id: '4', title: 'Deep work session — MindCast', time: '09:00', period: 'morning', done: false, aiGenerated: false, priority: 'high' },
  { id: '5', title: 'Check progress on active challenges', time: '12:30', period: 'afternoon', done: false, aiGenerated: true, priority: 'medium' },
  { id: '6', title: 'Afternoon walk (15 min)', time: '14:00', period: 'afternoon', done: false, aiGenerated: true, priority: 'medium' },
  { id: '7', title: 'Review analytics dashboard', time: '15:00', period: 'afternoon', done: false, aiGenerated: false, priority: 'high' },
  { id: '8', title: 'Evening journal reflection', time: '20:00', period: 'evening', done: false, aiGenerated: true, priority: 'high' },
  { id: '9', title: 'Wind-down routine — no screens', time: '22:00', period: 'evening', done: false, aiGenerated: true, priority: 'medium' },
  { id: '10', title: 'Sleep by 23:00', time: '23:00', period: 'evening', done: false, aiGenerated: true, priority: 'high' },
];

const PERIOD_CONFIG = {
  morning: { label: 'Morning', icon: Sun, color: 'text-amber-500', bg: 'bg-amber-500/10', border: 'border-amber-500/20' },
  afternoon: { label: 'Afternoon', icon: Sunset, color: 'text-sky-500', bg: 'bg-sky-500/10', border: 'border-sky-500/20' },
  evening: { label: 'Evening', icon: Moon, color: 'text-indigo-500', bg: 'bg-indigo-500/10', border: 'border-indigo-500/20' },
};

const PRIORITY_COLORS = {
  high: 'bg-rose-500/10 text-rose-600 dark:text-rose-400',
  medium: 'bg-amber-500/10 text-amber-600 dark:text-amber-400',
  low: 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400',
};

const containerVariants = {
  hidden: { opacity: 0 },
  visible: { opacity: 1, transition: { staggerChildren: 0.07 } },
};
const itemVariants = {
  hidden: { opacity: 0, y: 12 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.35, ease: 'easeOut' } },
};

export default function DailyPlannerContent() {
  const [tasks, setTasks] = useState<PlannerTask[]>(INITIAL_TASKS);
  const [dateStr, setDateStr] = useState('');
  const [greeting, setGreeting] = useState('');
  const [motivation, setMotivation] = useState('');
  const [regenerating, setRegenerating] = useState(false);

  useEffect(() => {
    const now = new Date();
    setDateStr(now.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' }));
    const hour = now.getHours();
    if (hour < 12) {
      setGreeting('Good morning');
      setMotivation('Start your day with intention. Your morning routine sets the tone for everything that follows.');
    } else if (hour < 17) {
      setGreeting('Good afternoon');
      setMotivation('You\'re halfway through. Check in with your progress and adjust your energy accordingly.');
    } else {
      setGreeting('Good evening');
      setMotivation('As the day winds down, reflect on your wins and prepare for restful recovery.');
    }
  }, []);

  const toggleTask = (id: string) => {
    setTasks((prev) => prev.map((t) => t.id === id ? { ...t, done: !t.done } : t));
  };

  const regeneratePlan = () => {
    setRegenerating(true);
    setTimeout(() => {
      setRegenerating(false);
      toast.success('Daily plan regenerated by MIRA! ✨');
    }, 1500);
  };

  const completedCount = tasks.filter((t) => t.done).length;
  const totalCount = tasks.length;
  const completionPct = Math.round((completedCount / totalCount) * 100);

  const periods: Array<'morning' | 'afternoon' | 'evening'> = ['morning', 'afternoon', 'evening'];

  return (
    <div className="px-5 lg:px-8 xl:px-10 py-7 pb-24 lg:pb-8 max-w-screen-xl mx-auto">
      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="mb-7">
        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Calendar size={20} strokeWidth={1.5} className="text-primary" />
              <h1 className="font-heading font-bold text-2xl lg:text-3xl text-foreground tracking-tight">Daily Planner</h1>
            </div>
            {dateStr && <p className="text-muted-foreground text-sm">{dateStr}</p>}
          </div>
          <button
            onClick={regeneratePlan}
            disabled={regenerating}
            className="btn-ghost border border-border text-sm flex items-center gap-2"
          >
            <Sparkles size={14} strokeWidth={1.5} className={regenerating ? 'animate-spin' : ''} />
            {regenerating ? 'Generating...' : 'Regenerate'}
          </button>
        </div>
      </motion.div>

      <motion.div variants={containerVariants} initial="hidden" animate="visible" className="space-y-5">
        {/* Motivation Card */}
        <motion.div variants={itemVariants} className="rounded-2xl border border-primary/20 bg-primary/5 p-5">
          <div className="flex items-start gap-3">
            <div className="w-9 h-9 rounded-xl bg-primary/15 flex items-center justify-center shrink-0">
              <Zap size={16} strokeWidth={1.5} className="text-primary" />
            </div>
            <div>
              <p className="text-xs font-semibold font-heading text-primary uppercase tracking-wider mb-1">MIRA · {greeting}</p>
              <p className="text-sm text-foreground leading-relaxed">{motivation}</p>
            </div>
          </div>
        </motion.div>

        {/* Progress */}
        <motion.div variants={itemVariants} className="rounded-2xl border border-border bg-card p-5">
          <div className="flex items-center justify-between mb-3">
            <div>
              <p className="text-sm font-semibold font-heading text-foreground">Today's Progress</p>
              <p className="text-xs text-muted-foreground">{completedCount} of {totalCount} tasks completed</p>
            </div>
            <span className="text-2xl font-bold font-heading text-foreground">{completionPct}%</span>
          </div>
          <div className="w-full h-2 rounded-full bg-border">
            <div
              className="h-full rounded-full bg-primary transition-all duration-700"
              style={{ width: `${completionPct}%` }}
            />
          </div>
        </motion.div>

        {/* Period Sections */}
        {periods.map((period) => {
          const cfg = PERIOD_CONFIG[period];
          const PeriodIcon = cfg.icon;
          const periodTasks = tasks.filter((t) => t.period === period);
          const periodDone = periodTasks.filter((t) => t.done).length;

          return (
            <motion.div key={period} variants={itemVariants} className={cn('rounded-2xl border p-5', cfg.border, cfg.bg)}>
              <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-2.5">
                  <div className={cn('w-8 h-8 rounded-xl flex items-center justify-center', cfg.bg)}>
                    <PeriodIcon size={16} strokeWidth={1.5} className={cfg.color} />
                  </div>
                  <h3 className="font-heading font-semibold text-sm text-foreground">{cfg.label}</h3>
                </div>
                <span className="text-xs font-semibold font-heading text-muted-foreground">{periodDone}/{periodTasks.length}</span>
              </div>

              <div className="space-y-2">
                {periodTasks.map((task) => (
                  <div
                    key={task.id}
                    className={cn(
                      'flex items-center gap-3 p-3 rounded-xl border bg-card/60 transition-all',
                      task.done ? 'border-border opacity-50' : 'border-border/50 hover:border-border'
                    )}
                  >
                    <button
                      onClick={() => toggleTask(task.id)}
                      className={cn(
                        'w-5 h-5 rounded-full border-2 flex items-center justify-center shrink-0 transition-all',
                        task.done ? 'border-emerald-500 bg-emerald-500' : 'border-muted-foreground/40 hover:border-primary'
                      )}
                    >
                      {task.done && <CheckCircle2 size={11} strokeWidth={3} className="text-white" />}
                    </button>

                    <div className="flex-1 min-w-0">
                      <p className={cn('text-sm font-medium text-foreground', task.done && 'line-through text-muted-foreground')}>{task.title}</p>
                    </div>

                    <div className="flex items-center gap-2 shrink-0">
                      {task.time && (
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <Clock size={10} strokeWidth={1.5} />
                          {task.time}
                        </span>
                      )}
                      {task.aiGenerated && (
                        <span className="text-[10px] font-semibold text-primary bg-primary/10 px-1.5 py-0.5 rounded-full">AI</span>
                      )}
                      <span className={cn('text-[10px] font-semibold px-1.5 py-0.5 rounded-full capitalize', PRIORITY_COLORS[task.priority])}>
                        {task.priority}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </motion.div>
          );
        })}

        {/* Evening Reflection Prompt */}
        <motion.div variants={itemVariants} className="rounded-2xl border border-indigo-500/20 bg-indigo-500/5 p-5">
          <div className="flex items-center gap-2 mb-3">
            <Moon size={15} strokeWidth={1.5} className="text-indigo-500" />
            <p className="text-sm font-semibold font-heading text-foreground">Tonight's Reflection</p>
          </div>
          <div className="space-y-2">
            {[
              'What went well today?',
              'What could have gone better?',
              'What was your biggest win?',
              'What are you grateful for?',
            ].map((q, i) => (
              <div key={i} className="flex items-center gap-2 text-sm text-muted-foreground">
                <ChevronRight size={13} strokeWidth={2} className="text-indigo-400 shrink-0" />
                {q}
              </div>
            ))}
          </div>
          <a href="/journal" className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-indigo-600 dark:text-indigo-400 hover:underline">
            Open Journal <ChevronRight size={12} strokeWidth={2} />
          </a>
        </motion.div>
      </motion.div>
    </div>
  );
}
